test: &default

  # Credentials for REST APIs
  client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  #app_id: APP-80W284485P519543T
  username: teenserv444_api1.gmail.com
  password: 42MAZDK877EB88Z8
  signature: ANb6Vvsm4q4CoMgtv0JqIsbytb5bAX7VEAd1FD0eJQOTrjx4d9uTM5W8
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: teenserv444@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default
  mode: sandbox

production:
  <<: *default
  mode: live
