test: &default

  # Credentials for REST APIs
  client_id: AaUlnPBTww3xJyQ9fcicrg9eJ7xlDg-FNmGzUCRRE5JK2pIlSOmXg8cs8gJ2LOmzUU8fIuvGVJGMrwwu
  client_secret: EP8A6VGdjFdAcd2Uz4woi7AWC86d85U6_SVV08HHKtknta59D0thAyvMHOQBesoMv-e35d_y_kskz3oz

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

development:
  <<: *default

production:
  <<: *default
  mode: live
